# Generated by Django 3.2.14 on 2022-11-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pañol_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='metros',
            field=models.IntegerField(blank=True),
        ),
    ]
